/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
*/


/*
 * Auto-generated by scripts not available in repository
 */

namespace QuantConnect.DataSource
{
    public partial class USDAFruitAndVegetables
    {
        public static class AcornSquash
        {
            public static string Fresh => "acorn_squash_fresh"; // Acorn squash - Fresh
        }

        public static class Apples
        {
            public static string Applesauce => "apples_applesauce"; // Apples - Applesauce
            public static string Fresh => "apples_fresh"; // Apples - Fresh
            public static string JuiceFrozen => "apples_juice_frozen"; // Apples - Juice, Frozen
            public static string JuiceReadyToDrink => "apples_juice_ready_to_drink"; // Apples - Juice, Ready to drink
        }

        public static class Apricots
        {
            public static string CannedDried => "apricots_canned_dried"; // Apricots - Canned, Dried
            public static string CannedPackedInJuice => "apricots_canned_packed_in_juice"; // Apricots - Canned, Packed in juice
            public static string CannedPackedInSyrupOrWater => "apricots_canned_packed_in_syrup_or_water"; // Apricots - Canned, Packed in syrup or water
            public static string CannedPackedInSyrupSyrupDiscarded => "apricots_canned_packed_in_syrup_syrup_discarded"; // Apricots - Canned, Packed in syrup, Syrup discarded
            public static string Dried => "apricots_dried"; // Apricots - Dried
            public static string Fresh => "apricots_fresh"; // Apricots - Fresh
        }

        public static class Artichoke
        {
            public static string Canned => "artichoke_canned"; // Artichoke - Canned
            public static string Fresh => "artichoke_fresh"; // Artichoke - Fresh
            public static string Frozen => "artichoke_frozen"; // Artichoke - Frozen
        }

        public static class Asparagus
        {
            public static string Canned => "asparagus_canned"; // Asparagus - Canned
            public static string Fresh => "asparagus_fresh"; // Asparagus - Fresh
            public static string Frozen => "asparagus_frozen"; // Asparagus - Frozen
        }

        public static class Avocados
        {
            public static string Fresh => "avocados_fresh"; // Avocados - Fresh
        }

        public static class Bananas
        {
            public static string Fresh => "bananas_fresh"; // Bananas - Fresh
        }

        public static class Beets
        {
            public static string Canned => "beets_canned"; // Beets - Canned
        }

        public static class BlackBeans
        {
            public static string Canned => "black_beans_canned"; // Black beans - Canned
            public static string Dried => "black_beans_dried"; // Black beans - Dried
        }

        public static class Blackberries
        {
            public static string Fresh => "blackberries_fresh"; // Blackberries - Fresh
            public static string Frozen => "blackberries_frozen"; // Blackberries - Frozen
        }

        public static class BlackeyePeas
        {
            public static string Canned => "blackeye_peas_canned"; // Blackeye peas - Canned
            public static string Dried => "blackeye_peas_dried"; // Blackeye peas - Dried
        }

        public static class Blueberries
        {
            public static string Fresh => "blueberries_fresh"; // Blueberries - Fresh
            public static string Frozen => "blueberries_frozen"; // Blueberries - Frozen
        }

        public static class Broccoli
        {
            public static string FreshFlorets => "broccoli_fresh_florets"; // Broccoli - Fresh, Florets
            public static string FreshFrozen => "broccoli_fresh_frozen"; // Broccoli - Fresh, Frozen
            public static string FreshHeads => "broccoli_fresh_heads"; // Broccoli - Fresh, Heads
            public static string Frozen => "broccoli_frozen"; // Broccoli - Frozen
        }

        public static class BrusselsSprouts
        {
            public static string Fresh => "brussels_sprouts_fresh"; // Brussels sprouts - Fresh
            public static string Frozen => "brussels_sprouts_frozen"; // Brussels sprouts - Frozen
        }

        public static class ButternutSquash
        {
            public static string Fresh => "butternut_squash_fresh"; // Butternut squash - Fresh
        }

        public static class Cabbage
        {
            public static string FreshGreenCabbage => "cabbage_fresh_green_cabbage"; // Cabbage - Fresh green cabbage
            public static string FreshRedCabbage => "cabbage_fresh_red_cabbage"; // Cabbage - Fresh red cabbage
            public static string Sauerkraut => "cabbage_sauerkraut"; // Cabbage - Sauerkraut
        }

        public static class Cantaloupe
        {
            public static string Fresh => "cantaloupe_fresh"; // Cantaloupe - Fresh
        }

        public static class Carrots
        {
            public static string Canned => "carrots_canned"; // Carrots - Canned
            public static string FreshCanned => "carrots_fresh_canned"; // Carrots - Fresh, Canned
            public static string FreshCookedWhole => "carrots_fresh_cooked_whole"; // Carrots - Fresh, Cooked whole
            public static string FreshFrozen => "carrots_fresh_frozen"; // Carrots - Fresh, Frozen
            public static string FreshRawBaby => "carrots_fresh_raw_baby"; // Carrots - Fresh, Raw baby
            public static string FreshRawWhole => "carrots_fresh_raw_whole"; // Carrots - Fresh, Raw whole
            public static string Frozen => "carrots_frozen"; // Carrots - Frozen
        }

        public static class Cauliflower
        {
            public static string FreshFlorets => "cauliflower_fresh_florets"; // Cauliflower - Fresh, Florets
            public static string FreshFrozen => "cauliflower_fresh_frozen"; // Cauliflower - Fresh, Frozen
            public static string FreshHeads => "cauliflower_fresh_heads"; // Cauliflower - Fresh, Heads
            public static string Frozen => "cauliflower_frozen"; // Cauliflower - Frozen
        }

        public static class Celery
        {
            public static string FreshSticks => "celery_fresh_sticks"; // Celery - Fresh, Sticks
            public static string FreshTrimmedBunches => "celery_fresh_trimmed_bunches"; // Celery - Fresh, Trimmed bunches
        }

        public static class Cherries
        {
            public static string CannedPackedInSyrupOrWater => "cherries_canned_packed_in_syrup_or_water"; // Cherries - Canned, Packed in syrup or water
            public static string Fresh => "cherries_fresh"; // Cherries - Fresh
        }

        public static class Clementines
        {
            public static string Fresh => "clementines_fresh"; // Clementines - Fresh
        }

        public static class CollardGreens
        {
            public static string Canned => "collard_greens_canned"; // Collard greens - Canned
            public static string Fresh => "collard_greens_fresh"; // Collard greens - Fresh
            public static string Frozen => "collard_greens_frozen"; // Collard greens - Frozen
        }

        public static class Cranberries
        {
            public static string Dried => "cranberries_dried"; // Cranberries - Dried
        }

        public static class Cucumbers
        {
            public static string FreshConsumedWithPeel => "cucumbers_fresh_consumed_with_peel"; // Cucumbers - Fresh, Consumed with peel
            public static string FreshPeeled => "cucumbers_fresh_peeled"; // Cucumbers - Fresh, Peeled
        }

        public static class Dates
        {
            public static string Dried => "dates_dried"; // Dates - Dried
        }

        public static class Figs
        {
            public static string Dried => "figs_dried"; // Figs - Dried
        }

        public static class FruitCocktail
        {
            public static string CannedInJuice => "fruit_cocktail_canned_in_juice"; // Fruit cocktail - Canned, In juice
            public static string CannedInSyrupOrWater => "fruit_cocktail_canned_in_syrup_or_water"; // Fruit cocktail - Canned, In syrup or water
            public static string CannedPackedInJuice => "fruit_cocktail_canned_packed_in_juice"; // Fruit cocktail - Canned, Packed in juice
            public static string CannedPackedInSyrupOrWater => "fruit_cocktail_canned_packed_in_syrup_or_water"; // Fruit cocktail - Canned, Packed in syrup or water
        }

        public static class Grapefruit
        {
            public static string Fresh => "grapefruit_fresh"; // Grapefruit - Fresh
            public static string JuiceFrozen => "grapefruit_juice_frozen"; // Grapefruit - Juice, Frozen
            public static string JuiceReadyToDrink => "grapefruit_juice_ready_to_drink"; // Grapefruit - Juice, Ready to drink
        }

        public static class Grapes
        {
            public static string Fresh => "grapes_fresh"; // Grapes - Fresh
            public static string JuiceFrozen => "grapes_juice_frozen"; // Grapes - Juice, Frozen
            public static string JuiceReadyToDrink => "grapes_juice_ready_to_drink"; // Grapes - Juice, Ready to drink
            public static string Raisins => "grapes_raisins"; // Grapes - Raisins
        }

        public static class GreatNorthernBeans
        {
            public static string Canned => "great_northern_beans_canned"; // Great northern beans - Canned
            public static string Dried => "great_northern_beans_dried"; // Great northern beans - Dried
        }

        public static class GreenBeans
        {
            public static string Canned => "green_beans_canned"; // Green beans - Canned
            public static string Fresh => "green_beans_fresh"; // Green beans - Fresh
            public static string Frozen => "green_beans_frozen"; // Green beans - Frozen
        }

        public static class GreenPeas
        {
            public static string Canned => "green_peas_canned"; // Green peas - Canned
            public static string Frozen => "green_peas_frozen"; // Green peas - Frozen
        }

        public static class GreenPeppers
        {
            public static string Fresh => "green_peppers_fresh"; // Green peppers - Fresh
        }

        public static class HoneydewMelon
        {
            public static string Fresh => "honeydew_melon_fresh"; // Honeydew melon - Fresh
        }

        public static class IcebergLettuce
        {
            public static string Fresh => "iceberg_lettuce_fresh"; // Iceberg lettuce - Fresh
        }

        public static class Kale
        {
            public static string Canned => "kale_canned"; // Kale - Canned
            public static string Fresh => "kale_fresh"; // Kale - Fresh
            public static string Frozen => "kale_frozen"; // Kale - Frozen
        }

        public static class KidneyBeans
        {
            public static string Canned => "kidney_beans_canned"; // Kidney beans - Canned
            public static string Dried => "kidney_beans_dried"; // Kidney beans - Dried
        }

        public static class Kiwi
        {
            public static string Fresh => "kiwi_fresh"; // Kiwi - Fresh
        }

        public static class Lentils
        {
            public static string Dried => "lentils_dried"; // Lentils - Dried
        }

        public static class LimaBeans
        {
            public static string Canned => "lima_beans_canned"; // Lima beans - Canned
            public static string Dried => "lima_beans_dried"; // Lima beans - Dried
            public static string Frozen => "lima_beans_frozen"; // Lima beans - Frozen
        }

        public static class Mangoes
        {
            public static string Dried => "mangoes_dried"; // Mangoes - Dried
            public static string Fresh => "mangoes_fresh"; // Mangoes - Fresh
        }

        public static class MixedBerries
        {
            public static string Frozen => "mixed_berries_frozen"; // Mixed berries - Frozen
        }

        public static class MixedVegetables
        {
            public static string CannedPeasAndCarrots => "mixed_vegetables_canned_peas_and_carrots"; // Mixed vegetables - Canned, Peas and carrots
            public static string FrozenBroccoliCauliflowerAndCarrots => "mixed_vegetables_frozen_broccoli_cauliflower_and_carrots"; // Mixed vegetables - Frozen, Broccoli, Cauliflower, And carrots
            public static string FrozenCarrotsPeasCornAndGreenBeans => "mixed_vegetables_frozen_carrots_peas_corn_and_green_beans"; // Mixed vegetables - Frozen, Carrots, Peas, Corn, And green beans
            public static string FrozenPeasAndCarrots => "mixed_vegetables_frozen_peas_and_carrots"; // Mixed vegetables - Frozen, Peas and carrots
            public static string GreenPeasCarrotsCanned => "mixed_vegetables_green_peas_carrots_canned"; // Mixed vegetables - Green peas & carrots, Canned
            public static string GreenPeasCarrotsFrozen => "mixed_vegetables_green_peas_carrots_frozen"; // Mixed vegetables - Green peas & carrots, Frozen
            public static string PeasCarrotsCanned => "mixed_vegetables_peas_carrots_canned"; // Mixed vegetables - Peas & carrots, Canned
            public static string PeasCarrotsFrozen => "mixed_vegetables_peas_carrots_frozen"; // Mixed vegetables - Peas & carrots, Frozen
            public static string PeasCarrotsFrozenBroccoliCauliflowerCarrot => "mixed_vegetables_peas_carrots_frozen_broccoli_cauliflower_carrot"; // Mixed vegetables - Peas & carrots, Frozen broccoli cauliflower carrot
            public static string PeasCarrotsFrozenCarrotPeaCornGreenBean => "mixed_vegetables_peas_carrots_frozen_carrot_pea_corn_green_bean"; // Mixed vegetables - Peas & carrots, Frozen carrot pea corn green bean
            public static string SuccotashCanned => "mixed_vegetables_succotash_canned"; // Mixed vegetables - Succotash, Canned
            public static string SuccotashFrozen => "mixed_vegetables_succotash_frozen"; // Mixed vegetables - Succotash, Frozen
        }

        public static class Mushrooms
        {
            public static string FreshSliced => "mushrooms_fresh_sliced"; // Mushrooms - Fresh, Sliced
            public static string FreshWhole => "mushrooms_fresh_whole"; // Mushrooms - Fresh, Whole
        }

        public static class MustardGreens
        {
            public static string Canned => "mustard_greens_canned"; // Mustard greens - Canned
            public static string Fresh => "mustard_greens_fresh"; // Mustard greens - Fresh
            public static string Frozen => "mustard_greens_frozen"; // Mustard greens - Frozen
        }

        public static class NavyBeans
        {
            public static string Canned => "navy_beans_canned"; // Navy beans - Canned
            public static string Dried => "navy_beans_dried"; // Navy beans - Dried
        }

        public static class Nectarines
        {
            public static string Fresh => "nectarines_fresh"; // Nectarines - Fresh
        }

        public static class Okra
        {
            public static string Fresh => "okra_fresh"; // Okra - Fresh
            public static string Frozen => "okra_frozen"; // Okra - Frozen
        }

        public static class Olives
        {
            public static string Canned => "olives_canned"; // Olives - Canned
        }

        public static class Onions
        {
            public static string Fresh => "onions_fresh"; // Onions - Fresh
        }

        public static class Oranges
        {
            public static string Fresh => "oranges_fresh"; // Oranges - Fresh
            public static string JuiceFrozen => "oranges_juice_frozen"; // Oranges - Juice, Frozen
            public static string JuiceReadyToDrink => "oranges_juice_ready_to_drink"; // Oranges - Juice, Ready to drink
        }

        public static class Papaya
        {
            public static string Dried => "papaya_dried"; // Papaya - Dried
            public static string Fresh => "papaya_fresh"; // Papaya - Fresh
        }

        public static class Peaches
        {
            public static string CannedFrozen => "peaches_canned_frozen"; // Peaches - Canned, Frozen
            public static string CannedInJuice => "peaches_canned_in_juice"; // Peaches - Canned, In juice
            public static string CannedInSyrupOrWater => "peaches_canned_in_syrup_or_water"; // Peaches - Canned, In syrup or water
            public static string CannedPackedInJuice => "peaches_canned_packed_in_juice"; // Peaches - Canned, Packed in juice
            public static string CannedPackedInSyrupOrWater => "peaches_canned_packed_in_syrup_or_water"; // Peaches - Canned, Packed in syrup or water
            public static string Fresh => "peaches_fresh"; // Peaches - Fresh
            public static string Frozen => "peaches_frozen"; // Peaches - Frozen
        }

        public static class Pears
        {
            public static string CannedInJuice => "pears_canned_in_juice"; // Pears - Canned, In juice
            public static string CannedInSyrupOrWater => "pears_canned_in_syrup_or_water"; // Pears - Canned, In syrup or water
            public static string CannedPackedInJuice => "pears_canned_packed_in_juice"; // Pears - Canned, Packed in juice
            public static string CannedPackedInSyrupOrWater => "pears_canned_packed_in_syrup_or_water"; // Pears - Canned, Packed in syrup or water
            public static string Fresh => "pears_fresh"; // Pears - Fresh
        }

        public static class Pineapple
        {
            public static string CannedDried => "pineapple_canned_dried"; // Pineapple - Canned, Dried
            public static string CannedInJuice => "pineapple_canned_in_juice"; // Pineapple - Canned, In juice
            public static string CannedInSyrupOrWater => "pineapple_canned_in_syrup_or_water"; // Pineapple - Canned, In syrup or water
            public static string CannedPackedInJuice => "pineapple_canned_packed_in_juice"; // Pineapple - Canned, Packed in juice
            public static string CannedPackedInSyrupOrWater => "pineapple_canned_packed_in_syrup_or_water"; // Pineapple - Canned, Packed in syrup or water
            public static string Dried => "pineapple_dried"; // Pineapple - Dried
            public static string Fresh => "pineapple_fresh"; // Pineapple - Fresh
            public static string JuiceFrozen => "pineapple_juice_frozen"; // Pineapple - Juice, Frozen
            public static string JuiceReadyToDrink => "pineapple_juice_ready_to_drink"; // Pineapple - Juice, Ready to drink
        }

        public static class PintoBeans
        {
            public static string Canned => "pinto_beans_canned"; // Pinto beans - Canned
            public static string Dried => "pinto_beans_dried"; // Pinto beans - Dried
        }

        public static class Plums
        {
            public static string DriedPrunes => "plums_dried_prunes"; // Plums - Dried (Prunes)
            public static string Fresh => "plums_fresh"; // Plums - Fresh
            public static string JuicePruneReadyToDrink => "plums_juice_prune_ready_to_drink"; // Plums - Juice (Prune), Ready to drink
            public static string JuiceReadyToDrink => "plums_juice_ready_to_drink"; // Plums - Juice, Ready to drink
        }

        public static class Pomegranate
        {
            public static string Fresh => "pomegranate_fresh"; // Pomegranate - Fresh
            public static string JuiceReadyToDrink => "pomegranate_juice_ready_to_drink"; // Pomegranate - Juice, Ready to drink
        }

        public static class Potatoes
        {
            public static string Canned => "potatoes_canned"; // Potatoes - Canned
            public static string Fresh => "potatoes_fresh"; // Potatoes - Fresh
            public static string FrozenFrenchFries => "potatoes_frozen_french_fries"; // Potatoes - Frozen french fries
        }

        public static class Pumpkin
        {
            public static string Canned => "pumpkin_canned"; // Pumpkin - Canned
        }

        public static class Radish
        {
            public static string Fresh => "radish_fresh"; // Radish - Fresh
        }

        public static class Raspberries
        {
            public static string Fresh => "raspberries_fresh"; // Raspberries - Fresh
            public static string Frozen => "raspberries_frozen"; // Raspberries - Frozen
        }

        public static class RedPeppers
        {
            public static string Fresh => "red_peppers_fresh"; // Red peppers - Fresh
        }

        public static class RomaineLettuce
        {
            public static string FreshFullHeads => "romaine_lettuce_fresh_full_heads"; // Romaine lettuce - Fresh, Full heads
            public static string FreshHearts => "romaine_lettuce_fresh_hearts"; // Romaine lettuce - Fresh, Hearts
        }

        public static class Spinach
        {
            public static string Canned => "spinach_canned"; // Spinach - Canned
            public static string FreshBoiled => "spinach_fresh_boiled"; // Spinach - Fresh, Boiled
            public static string FreshCanned => "spinach_fresh_canned"; // Spinach - Fresh, Canned
            public static string FreshFrozen => "spinach_fresh_frozen"; // Spinach - Fresh, Frozen
            public static string FreshRaw => "spinach_fresh_raw"; // Spinach - Fresh, Raw
            public static string Frozen => "spinach_frozen"; // Spinach - Frozen
        }

        public static class Strawberries
        {
            public static string Fresh => "strawberries_fresh"; // Strawberries - Fresh
            public static string Frozen => "strawberries_frozen"; // Strawberries - Frozen
        }

        public static class SummerSquash
        {
            public static string Fresh => "summer_squash_fresh"; // Summer squash - Fresh
        }

        public static class SweetCorn
        {
            public static string Canned => "sweet_corn_canned"; // Sweet corn - Canned
            public static string Fresh => "sweet_corn_fresh"; // Sweet corn - Fresh
            public static string Frozen => "sweet_corn_frozen"; // Sweet corn - Frozen
        }

        public static class SweetPotatoes
        {
            public static string Fresh => "sweet_potatoes_fresh"; // Sweet potatoes - Fresh
        }

        public static class Tangerines
        {
            public static string Fresh => "tangerines_fresh"; // Tangerines - Fresh
        }

        public static class Tomatoes
        {
            public static string Canned => "tomatoes_canned"; // Tomatoes - Canned
            public static string FreshBeefsteak => "tomatoes_fresh_beefsteak"; // Tomatoes - Fresh, Beefsteak
            public static string FreshCanned => "tomatoes_fresh_canned"; // Tomatoes - Fresh, Canned
            public static string FreshGrapeAndCherry => "tomatoes_fresh_grape_and_cherry"; // Tomatoes - Fresh, Grape and cherry
            public static string FreshLargeRound => "tomatoes_fresh_large_round"; // Tomatoes - Fresh, Large round
            public static string FreshRoma => "tomatoes_fresh_roma"; // Tomatoes - Fresh, Roma
            public static string FreshRomaAndPlum => "tomatoes_fresh_roma_and_plum"; // Tomatoes - Fresh, Roma and plum
        }

        public static class TurnipGreens
        {
            public static string Canned => "turnip_greens_canned"; // Turnip greens - Canned
            public static string Fresh => "turnip_greens_fresh"; // Turnip greens - Fresh
            public static string Frozen => "turnip_greens_frozen"; // Turnip greens - Frozen
        }

        public static class Watermelon
        {
            public static string Fresh => "watermelon_fresh"; // Watermelon - Fresh
        }

        public static class Zucchini
        {
            public static string Fresh => "zucchini_fresh"; // Zucchini - Fresh
        }

    }
}
